const data = {
  products: [
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      ratting: 4.5,
      numReviews: 10,
      desciption: 'high quality shirt',
    },
    {
      name: 'Adidas fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      ratting: 4.0,
      numReviews: 10,
      desciption: 'high quality shirt',
    },
    {
      name: 'nike slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      ratting: 4.5,
      numReviews: 14,
      desciption: 'high quality product',
    },
    {
      name: 'Adidas Fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      ratting: 4.5,
      numReviews: 10,
      desciption: 'high quality product',
    },
  ],
};
export default data;
